// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is the editable local Provider record. APIKey is returned only by the
 * explicit Provider CRUD service; status projections expose HasKey instead.
 */
export interface Entry {
    "id": string;
    "name": string;
    "home": string;

    /**
     * Both derived from the built-in catalog, not user-editable: a user who adds
     * a Provider supplies Home, and a custom endpoint has no model we can vouch
     * for. Serialized so the frontend can pre-fill the model field and aim the
     * key button at a key page instead of a marketing site.
     */
    "key_management_url"?: string;
    "default_model"?: string;
    "base_url": string;
    "anthropic_base_url": string;
    "api_key": string;
    "built_in": boolean;
}
