// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is the editable local Provider record. APIKey is returned only by the
 * explicit Provider CRUD service; status projections expose HasKey instead.
 */
export interface Entry {
    "id": string;
    "name": string;
    "home": string;
    "base_url": string;
    "anthropic_base_url": string;
    "api_key": string;
    "built_in": boolean;
}
