// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Activate(request: $models.ActivateRequest): $CancellablePromise<$models.ActivateResponse> {
    return $Call.ByID(1962001654, request);
}

export function Install(request: $models.InstallRequest): $CancellablePromise<$models.InstallResponse> {
    return $Call.ByID(3913480362, request);
}

/**
 * Launch opens a terminal window running one Agent with its OneAgent
 * configuration already sourced.
 */
export function Launch(request: $models.LaunchRequest): $CancellablePromise<$models.LaunchResponse> {
    return $Call.ByID(1510250212, request);
}

export function Update(request: $models.UpdateRequest): $CancellablePromise<app$0.AgentUpdateResult> {
    return $Call.ByID(444770282, request);
}
