// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopAppService exposes the official ChatGPT Desktop lifecycle. It does
 * not own or rewrite ~/.codex; the existing Agent configuration use cases do.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

export function GetStatus(): $CancellablePromise<app$0.ChatGPTAppStatus> {
    return $Call.ByID(2919355991);
}

export function Install(): $CancellablePromise<app$0.ChatGPTAppActionResult> {
    return $Call.ByID(3280788338);
}

export function Open(): $CancellablePromise<void> {
    return $Call.ByID(177612239);
}

export function OpenInstaller(): $CancellablePromise<app$0.ChatGPTAppActionResult> {
    return $Call.ByID(2316413953);
}
