// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopAgentService exposes the configured desktop agent lifecycle. It does
 * not own or rewrite ~/.codex; the existing Agent configuration use cases do.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Configure applies a saved Profile to the selected desktop Agent. The profile
 * ID is the only user-supplied value; secrets stay in the Go profile store.
 */
export function Configure(request: $models.DesktopAgentProfileRequest): $CancellablePromise<app$0.DesktopAgentProfileResult> {
    return $Call.ByID(1718807223, request);
}

export function GetStatus(): $CancellablePromise<app$0.DesktopAgentStatus> {
    return $Call.ByID(2070814877);
}

export function GetStatusFor(request: $models.DesktopAgentRequest): $CancellablePromise<app$0.DesktopAgentStatus> {
    return $Call.ByID(2496604744, request);
}

export function Install(): $CancellablePromise<app$0.DesktopAgentActionResult> {
    return $Call.ByID(3711371820);
}

export function InstallFor(request: $models.DesktopAgentRequest): $CancellablePromise<app$0.DesktopAgentActionResult> {
    return $Call.ByID(3526684419, request);
}

export function Open(): $CancellablePromise<void> {
    return $Call.ByID(1641870549);
}

export function OpenFor(request: $models.DesktopAgentRequest): $CancellablePromise<void> {
    return $Call.ByID(1541039616, request);
}

export function OpenInstaller(): $CancellablePromise<app$0.DesktopAgentActionResult> {
    return $Call.ByID(693638919);
}

export function OpenInstallerFor(request: $models.DesktopAgentRequest): $CancellablePromise<app$0.DesktopAgentActionResult> {
    return $Call.ByID(2134742642, request);
}
