// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Apply(request: app$0.MCPApplyRequest): $CancellablePromise<app$0.MCPApplyResult> {
    return $Call.ByID(1122671950, request);
}

export function Export(request: $models.MCPExportRequest): $CancellablePromise<string> {
    return $Call.ByID(1156741564, request);
}

export function Get(id: string, sourceAgent: string): $CancellablePromise<app$0.MCPServerDetail> {
    return $Call.ByID(2848286610, id, sourceAgent);
}

export function List(): $CancellablePromise<app$0.MCPServerSummary[] | null> {
    return $Call.ByID(934006466);
}

export function PreviewImport(request: $models.MCPImportRequest): $CancellablePromise<mcp$0.Registry> {
    return $Call.ByID(3912742423, request);
}

export function SaveImported(registry: mcp$0.Registry): $CancellablePromise<void> {
    return $Call.ByID(3700198299, registry);
}

export function Scan(): $CancellablePromise<app$0.MCPScanResult> {
    return $Call.ByID(3620222707);
}

export function SetDraftState(dirty: boolean, locale: string): $CancellablePromise<void> {
    return $Call.ByID(3453125470, dirty, locale);
}
