// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActivateRequest {
    "agent_id": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "profile_id": string;
    "small_fast_model": string;
}

export interface ActivateResponse {
    "ok": boolean;
    "agent": string;
    "config": string;
    "provider": string;
    "model": string;
    "restart": string;
    "next": string;
}

export interface AgentInstallResult {
    "agent": string;
    "status": string;
    "installed"?: boolean;
    "version"?: string;
    "lockedVersion"?: string;
    "registry"?: string;
    "config"?: string;
    "code"?: number;
    "error_code"?: string;
    "message"?: string;
    "retryable": boolean;
}

export interface InstallRequest {
    "agents": string[] | null;
    "profile_agents": string[] | null;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "small_fast_model": string;
    "profile_id": string;
    "configure": boolean;
    "install_agent": boolean;
    "locked_version": boolean;
    "latest": boolean;
    "skip_test": boolean;
    "registry": string;
    "timeout": number;
}

export interface InstallResponse {
    "ok": boolean;
    "code": number;
    "results": AgentInstallResult[] | null;
    "log": string;
    "next": string;
    "probe": ProbeResponse | null;
    "probes": { [_ in string]?: ProbeResponse } | null;
}

export interface ModelsRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
}

export interface ModelsResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;
    "models": string[] | null;
}

export interface OpenRegistrationRequest {
    "provider": string;
    "agents": string[] | null;
}

export interface OpenRegistrationResponse {
    "ok": boolean;
    "url": string;
    "message": string;
}

export interface ProbeRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "agents": string[] | null;
}

export interface ProbeResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;
}

export interface SaveProfileRequest {
    "id": string;
    "label": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "config_mode": string;
    "agent_ids": string[] | null;
}
