// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActivateRequest {
    "agent_id": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "profile_id": string;
    "small_fast_model": string;
}

export interface ActivateResponse {
    "ok": boolean;
    "agent": string;
    "config": string;
    "provider": string;
    "model": string;
    "restart": string;
    "next": string;
}

export interface AgentInstallResult {
    "agent": string;
    "status": string;
    "config"?: string | null;
    "installed"?: boolean | null;
    "version"?: string | null;
    "lockedVersion"?: string | null;
    "registry"?: string | null;
    "code"?: number | null;
    "error_code"?: string | null;
    "message"?: string | null;
    "retryable": boolean;
}

export interface DesktopAgentProfileRequest {
    "agent_id": string;
    "profile_id": string;
}

export interface InstallRequest {
    "agents": string[] | null;
    "profile_agents": string[] | null;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "small_fast_model": string;
    "profile_id": string;
    "profile_label": string;
    "configure": boolean;
    "install_agent": boolean;
    "agent_version": string;
    "skip_test": boolean;
    "registry": string;
    "timeout": number;
}

export interface InstallResponse {
    "ok": boolean;
    "code": number;
    "results": AgentInstallResult[] | null;
    "log": string;
    "next": string;
    "probe": ProbeResponse | null;
    "probes": { [_ in string]?: ProbeResponse } | null;
}

export interface InstallRuntimeRequest {
    "runtime": string;
}

export interface LaunchRequest {
    "agent_id": string;
}

export interface LaunchResponse {
    "ok": boolean;
    "agent": string;
    "command": string;
}

export interface ModelsRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
}

export interface ModelsResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;
    "models": string[] | null;
}

export interface OpenRegistrationRequest {
    "provider": string;
    "agents": string[] | null;
}

export interface OpenRegistrationResponse {
    "ok": boolean;
    "url": string;
    "message": string;
}

export interface ProbeRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "agents": string[] | null;
}

export interface ProbeResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;
}

export interface ProviderIDRequest {
    "id": string;
}

export interface ProviderMutationResponse {
    "ok": boolean;
}

export interface SaveProfileRequest {
    "id": string;
    "label": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "config_mode": string;
    "protocol": string;
    "agent_ids": string[] | null;
}

export interface SaveProviderRequest {
    "id": string;
    "name": string;
    "home": string;
    "base_url": string;
    "anthropic_base_url": string;
    "api_key": string;
}

export interface UpdateRequest {
    "agent_id": string;
}
