// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ActivateRequest {
    "agent_id": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "profile_id": string;
    "small_fast_model": string;
}

export interface ActivateResponse {
    "ok": boolean;
    "agent": string;
    "config": string;
    "provider": string;
    "model": string;
    "restart": string;
    "next": string;
}

export interface AgentInstallResult {
    "agent": string;
    "status": string;
    "config"?: string | null;
    "installed"?: boolean | null;
    "version"?: string | null;
    "lockedVersion"?: string | null;
    "registry"?: string | null;
    "code"?: number | null;
    "error_code"?: string | null;
    "message"?: string | null;
    "retryable": boolean;
}

export interface DesktopAgentProfileRequest {
    "agent_id": string;
    "profile_id": string;
}

export interface DesktopAgentRequest {
    "agent_id": string;
}

export interface InstallRequest {
    "agents": string[] | null;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "small_fast_model": string;
    "profile_id": string;
    "profile_label": string;
    "configure": boolean;
    "install_agent": boolean;
    "agent_version": string;
    "skip_test": boolean;
    "registry": string;
    "timeout": number;
}

export interface InstallResponse {
    "ok": boolean;
    "code": number;
    "results": AgentInstallResult[] | null;
    "log": string;
    "next": string;
    "probe": ProbeResponse | null;
    "probes": { [_ in string]?: ProbeResponse } | null;
}

export interface InstallRuntimeRequest {
    "runtime": string;
}

export interface LaunchRequest {
    "agent_id": string;
    "working_directory": string;
}

export interface LaunchResponse {
    "ok": boolean;
    "agent": string;
    "command": string;
}

export interface MCPExportRequest {
    "mode": string;
    "password"?: string;
    "confirm_plaintext"?: boolean;
}

export interface MCPImportRequest {
    "data": string | null;
    "password"?: string;
}

export interface ModelsRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
}

export interface ModelsResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;

    /**
     * Model is the ID that was probed, and AutoSelectedModel says OneAgent chose
     * it rather than the user. A failure on a model we picked is not evidence
     * about the user's key, and the UI has to be able to say which it is.
     */
    "model"?: string;
    "auto_selected_model"?: boolean;
    "models": string[] | null;
}

export interface OpenRegistrationRequest {
    "provider": string;
    "agents": string[] | null;
}

export interface OpenRegistrationResponse {
    "ok": boolean;
    "url": string;
    "message": string;
}

export interface ProbeRequest {
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "agents": string[] | null;

    /**
     * AnthropicBaseURL and Draft let the Provider editor test what is on screen
     * before it is saved. Draft is explicit rather than inferred from a non-empty
     * base URL: the wizard also sends a base URL, and silently switching it to
     * draft resolution would stop it reading the stored record.
     */
    "anthropic_base_url": string;
    "draft": boolean;
}

export interface ProbeResponse {
    "ok": boolean;
    "reachable": boolean;
    "status": number;
    "message": string;
    "error_code": string | null;
    "retryable": boolean;
    "protocol"?: string | null;
    "protocols"?: { [_ in string]?: ProbeResponse } | null;

    /**
     * Model is the ID that was probed, and AutoSelectedModel says OneAgent chose
     * it rather than the user. A failure on a model we picked is not evidence
     * about the user's key, and the UI has to be able to say which it is.
     */
    "model"?: string;
    "auto_selected_model"?: boolean;
}

export interface ProviderIDRequest {
    "id": string;
}

export interface ProviderMutationResponse {
    "ok": boolean;
}

export interface SaveProfileRequest {
    "id": string;
    "label": string;
    "provider": string;
    "api_base_url": string;
    "api_key": string;
    "model": string;
    "config_mode": string;
    "protocol": string;
}

export interface SaveProviderRequest {
    "id": string;
    "name": string;
    "home": string;
    "base_url": string;
    "anthropic_base_url": string;
    "api_key": string;

    /**
     * Create refuses an ID that already exists rather than overwriting it. It
     * defaults to false so an edit, which legitimately writes over an existing
     * entry, is the behaviour a caller gets without asking.
     */
    "create": boolean;

    /**
     * KeepExistingKey leaves a stored key in place when APIKey is empty, for an
     * import of a file exported without keys. Defaults to false so the Provider
     * editor keeps clearing the key when the user empties the field.
     */
    "keep_existing_key": boolean;
}

export interface UpdateRequest {
    "agent_id": string;
}
