// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListProfiles(): $CancellablePromise<app$0.ProfileSummary[] | null> {
    return $Call.ByID(192725737);
}

export function SaveProfile(request: $models.SaveProfileRequest): $CancellablePromise<app$0.ProfileSummary> {
    return $Call.ByID(972252911, request);
}
