// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListModels(request: $models.ModelsRequest): $CancellablePromise<$models.ModelsResponse> {
    return $Call.ByID(1201530915, request);
}

export function OpenRegistration(request: $models.OpenRegistrationRequest): $CancellablePromise<$models.OpenRegistrationResponse> {
    return $Call.ByID(745368128, request);
}

export function Probe(request: $models.ProbeRequest): $CancellablePromise<$models.ProbeResponse> {
    return $Call.ByID(2223638197, request);
}
