// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteProvider(request: $models.ProviderIDRequest): $CancellablePromise<$models.ProviderMutationResponse> {
    return $Call.ByID(116920211, request);
}

export function GetProvider(request: $models.ProviderIDRequest): $CancellablePromise<provider$0.Entry> {
    return $Call.ByID(36265922, request);
}

export function ListModels(request: $models.ModelsRequest): $CancellablePromise<$models.ModelsResponse> {
    return $Call.ByID(1201530915, request);
}

export function OpenRegistration(request: $models.OpenRegistrationRequest): $CancellablePromise<$models.OpenRegistrationResponse> {
    return $Call.ByID(745368128, request);
}

export function Probe(request: $models.ProbeRequest): $CancellablePromise<$models.ProbeResponse> {
    return $Call.ByID(2223638197, request);
}

export function SaveProvider(request: $models.SaveProviderRequest): $CancellablePromise<app$0.SaveProviderResult> {
    return $Call.ByID(2790810113, request);
}
