// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeService exposes the Node.js and uv bootstrap. It reuses the install
 * output listener so the UI shows runtime downloads in the same log pane as
 * Agent installs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function InstallRuntime(request: $models.InstallRuntimeRequest): $CancellablePromise<app$0.InstallRuntimeResult> {
    return $Call.ByID(2509127327, request);
}

export function ListRuntimes(): $CancellablePromise<app$0.RuntimeStatus[] | null> {
    return $Call.ByID(1068151511);
}
