// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService is the narrow Wails boundary for the local Skills registry.
 * Source paths are selected here and never cross into renderer state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

export function Apply(request: app$0.SkillApplyRequest): $CancellablePromise<app$0.SkillApplyResult> {
    return $Call.ByID(2463384701, request);
}

export function Get(id: string): $CancellablePromise<app$0.SkillSummary> {
    return $Call.ByID(1002729909, id);
}

export function List(): $CancellablePromise<app$0.SkillSummary[] | null> {
    return $Call.ByID(1006911811);
}

export function ListBackups(): $CancellablePromise<app$0.SkillBackupSummary[] | null> {
    return $Call.ByID(835707622);
}

export function PreviewImport(request: app$0.SkillImportRequest): $CancellablePromise<app$0.SkillImportPreview> {
    return $Call.ByID(312806924, request);
}

export function RestoreBackup(backupID: string, targets: string[] | null): $CancellablePromise<app$0.SkillApplyResult> {
    return $Call.ByID(3829087753, backupID, targets);
}

export function Scan(): $CancellablePromise<app$0.SkillScanResult> {
    return $Call.ByID(3527103466);
}

export function SetDraftState(dirty: boolean, locale: string): $CancellablePromise<void> {
    return $Call.ByID(2147275381, dirty, locale);
}

export function Uninstall(id: string): $CancellablePromise<app$0.SkillUninstallResult> {
    return $Call.ByID(1356241015, id);
}
