// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CatalogItem {
    "id": string;
    "name": string;
    "group": string;
    "configMode": string;

    /**
     * SelectsModel is false when the Agent owns its own model choice, so the
     * wizard can skip that step. Derived from Agent.ModelSelection rather than
     * exposed raw: the UI needs the decision, not the vocabulary, and a bool it
     * cannot misread beats a string it can compare against the wrong literal.
     */
    "selectsModel": boolean;

    /**
     * WebApp is true when launching this Agent ends in the browser rather than in
     * a terminal window. The UI uses it to skip the launch-directory prompt: the
     * Agent serves a local web app and picks its own workspace, so a directory
     * asked for there would be collected and then ignored.
     */
    "webApp": boolean;
    "guideOnly": boolean;
    "lockedVersion": string | null;
    "protocol": string | null;
    "platforms": string[] | null;
    "platformNote": string;
    "rank": number;

    /**
     * PackageManager and PackageName describe how this Agent is installed, so the
     * UI can decide whether to offer an update without keeping its own list of
     * npm Agents. That list existed and had already drifted: OpenClaw shipped as
     * an npm Agent and was missing from it, so it silently lost its update
     * button. Empty means the Agent has no package contract.
     */
    "packageManager"?: string;
    "packageName"?: string;
}

export interface Group {
    "id": string;
    "name": string;
}

export interface MarketplaceItem {
    "id": string;
    "category": string;
    "categories"?: string[] | null;
    "type": string;
    "name": string;
    "description": string;
    "descriptionEn"?: string;
    "icon": string;
    "iconColor": string;
    "tags"?: string[] | null;
    "tagKeys"?: string[] | null;
    "capabilities"?: string[] | null;
    "integrations"?: string[] | null;
    "deploymentModes"?: string[] | null;
    "trustLevel"?: string;
    "license"?: string;
    "updatedAt"?: string;
    "scene"?: string;
    "scenes"?: string[] | null;
    "source"?: string;
    "requiresApiKey"?: boolean;
    "sourceLabel"?: string;
    "sourceUrl"?: string;
    "repositoryUrl"?: string;
    "documentationUrl"?: string;
    "installationUrl"?: string;
    "installableKind"?: string;
    "installPrompt"?: string;
    "targetHint"?: string;
    "externalUrl"?: string;
    "readmeUrl"?: string;
    "iconUrl"?: string;
    "socialPreviewUrl"?: string;
    "stars"?: number;
    "downloads"?: number;
    "score"?: number;
    "githubStars"?: number;
    "githubForks"?: number;
    "githubLicense"?: string;
    "githubUpdatedAt"?: string;
}

export interface MarketplaceManifest {
    "schema_version": number;
    "version": string;
    "built_at": string;
    "items": MarketplaceItem[] | null;
}

export interface Mirror {
    "id": string;
    "name": string;
    "registry": string;
    "upstream": string;
    "note": string;
}

export interface Provider {
    "name": string;
    "home": string;

    /**
     * KeyManagementURL and DefaultModel are public on purpose: the frontend
     * needs both to spare a first-time user from hunting for a key page and
     * inventing a model ID. Contrast fallbackModel below.
     */
    "key_management_url"?: string;
    "base_url": string;
    "anthropic_base_url"?: string;
    "default_model"?: string;

    /**
     * Display precedence among built-in Providers, ascending. Absent for a
     * custom Provider, which the frontend sorts by creation time instead.
     */
    "order"?: number;
    "custom"?: boolean;
    "has_key"?: boolean;
    "created_at"?: string;
}
