// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CatalogItem {
    "id": string;
    "name": string;
    "group": string;
    "configMode": string;
    "guideOnly": boolean;
    "lockedVersion": string | null;
    "protocol": string | null;
    "platforms": string[] | null;
    "platformNote": string;
    "rank": number;

    /**
     * PackageManager and PackageName describe how this Agent is installed, so the
     * UI can decide whether to offer an update without keeping its own list of
     * npm Agents. That list existed and had already drifted: OpenClaw shipped as
     * an npm Agent and was missing from it, so it silently lost its update
     * button. Empty means the Agent has no package contract.
     */
    "packageManager"?: string;
    "packageName"?: string;
}

export interface Group {
    "id": string;
    "name": string;
}

export interface Mirror {
    "id": string;
    "name": string;
    "registry": string;
    "upstream": string;
    "note": string;
}

export interface Provider {
    "name": string;
    "home": string;

    /**
     * KeyManagementURL and DefaultModel are public on purpose: the frontend
     * needs both to spare a first-time user from hunting for a key page and
     * inventing a model ID. Contrast fallbackModel below.
     */
    "key_management_url"?: string;
    "base_url": string;
    "anthropic_base_url"?: string;
    "default_model"?: string;
    "custom"?: boolean;
    "has_key"?: boolean;
    "created_at"?: string;
}
