// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";

export interface AgentStatus {
    "installed": boolean;
    "configured": boolean;
    "guideOnly": boolean;
    "config": string;
    "version": string | null;
    "lockedVersion": string | null;
    "canInstall": boolean;
    "provider": string | null;
    "model": string | null;
    "baseUrl": string | null;
    "updatedAt": string | null;
    "detected": DetectedConfig | null;
}

export interface Capabilities {
    "canInstall": { [_ in string]?: boolean } | null;
    "supportedAgentIds": string[] | null;
}

export interface DetectedConfig {
    "baseUrl": string;
    "model": string;
    "managedByOneAgent": boolean;
    "unreadable": string | null;
}

/**
 * ProfileSummary is intentionally a public projection. It has no credential
 * field; hasKey only reports whether a secret exists in the secure store.
 */
export interface ProfileSummary {
    "id": string;
    "label": string;
    "provider": string;
    "baseUrl": string | null;
    "model": string | null;
    "agentIds": string[] | null;
    "activatedAt": string | null;
    "hasKey": boolean;
}

export interface StatusResponse {
    "apiVersion": number;
    "platform": platform$0.Info;
    "capabilities": Capabilities;
    "agents": { [_ in string]?: AgentStatus } | null;
    "catalog": catalog$0.CatalogItem[] | null;
    "groups": catalog$0.Group[] | null;
    "providers": { [_ in string]?: catalog$0.Provider } | null;
    "mirrors": catalog$0.Mirror[] | null;
    "paths": { [_ in string]?: string } | null;
    "backups": { [_ in string]?: boolean } | null;
    "profiles": ProfileSummary[] | null;
    "activeProfile": string | null;
    "environment": any;
    "environmentError": string | null;
}
