// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as install$0 from "../install/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

export interface AgentStatus {
    "installed": boolean;
    "configured": boolean;
    "guideOnly": boolean;
    "config": string;
    "version": string | null;
    "lockedVersion": string | null;
    "canInstall": boolean;
    "provider": string | null;
    "profileId": string | null;
    "model": string | null;
    "baseUrl": string | null;
    "updatedAt": string | null;
    "detected": DetectedConfig | null;
}

export interface AgentUpdateResult {
    "agent": string;
    "package": string;
    "command": string;
}

export interface Capabilities {
    "canInstall": { [_ in string]?: boolean } | null;

    /**
     * MissingRuntime names the runtime an Agent needs before it can be
     * installed, keyed by Agent id. An entry means canInstall is false only
     * because a bootstrappable runtime is absent, which the UI turns into a
     * "install the runtime first" prompt rather than a dead end.
     */
    "missingRuntime": { [_ in string]?: string } | null;
    "supportedAgentIds": string[] | null;
}

/**
 * DesktopAgentActionResult reports a local installation action. Windows Store
 * installation continues after its downloaded bootstrapper starts.
 */
export interface DesktopAgentActionResult {
    "status": string;
    "message": string;
    "refreshNeeded": boolean;
    "app": DesktopAgentStatus;
}

/**
 * DesktopAgentProfileResult is the non-secret result of applying a saved
 * profile to a desktop Agent.
 */
export interface DesktopAgentProfileResult {
    "agent": string;
    "profileId": string;
    "profileAgentId": string;
    "config"?: string;
    "restart"?: string;
    "message": string;
}

/**
 * DesktopAgentStatus is the public projection of the current desktop agent. It is
 * deliberately separate from AgentStatus: desktop and command-line agents may
 * share config, but they have different installation and version contracts.
 */
export interface DesktopAgentStatus {
    "id": string;
    "name": string;
    "installed": boolean;
    "supported": boolean;
    "path"?: string;
    "version": string | null;
    "source": string;
    "configPath"?: string;
    "configSharedWith"?: string;
    "protocol"?: string;
    "profileAgentId": string;
    "profileId": string | null;
    "packageFamily"?: string;
    "inspectionUnavailable"?: string | null;
}

export interface DetectedConfig {
    "baseUrl": string;
    "model": string;
    "managedByOneAgent": boolean;
    "unreadable": string | null;
}

/**
 * InstallRuntimeResult reports what the bootstrap did. PathUpdated is separate
 * from Installed because an already-downloaded runtime may still need its
 * directory recorded on the login PATH.
 */
export interface InstallRuntimeResult {
    "runtime": string;
    "installed": boolean;
    "version": string;
    "pathUpdated": boolean;
    "runtimes": RuntimeStatus[] | null;
}

/**
 * ProfileSummary is intentionally a public projection. It has no credential
 * field; hasKey only reports whether a secret exists in the secure store.
 */
export interface ProfileSummary {
    "id": string;
    "label": string;
    "provider": string;
    "baseUrl": string | null;
    "model": string | null;
    "protocol": string;
    "activatedAt": string | null;
    "hasKey": boolean;
    "createdAt"?: string;
}

/**
 * RuntimeStatus is the public projection of one bootstrappable runtime.
 */
export type RuntimeStatus = install$0.RuntimeState;

/**
 * SaveProviderResult reports which Agents were rewritten after the edit so the
 * UI can say so, and which ones could not be, keyed by Agent ID.
 */
export interface SaveProviderResult {
    "entry": provider$0.Entry;
    "reapplied": string[] | null;
    "failures": { [_ in string]?: string } | null;
}

/**
 * Settings holds machine-level preferences that are not part of a profile and
 * not secret. It is deliberately tiny: a preference belongs here only when both
 * the desktop app and the CLI need it and it must outlive one request.
 */
export interface Settings {
    "schema_version": number;

    /**
     * PreferMirror routes runtime archives through the mirror in
     * runtimes.lock.json and npm-managed Agents through the npmmirror registry.
     * Runtime archives keep their locked checksum verification; npm verifies
     * packages using the selected registry's metadata. uv is unaffected.
     */
    "prefer_mirror": boolean;

    /**
     * MirrorFromRegion reports that PreferMirror above is a region-derived
     * default rather than the user's own choice. The UI uses it to explain why
     * the box is already ticked. It is never persisted: it is recomputed from the
     * machine each read, and storing it would let a stale answer outlive the
     * setting that produced it.
     */
    "mirror_from_region": boolean;
}

export interface StatusResponse {
    "apiVersion": number;
    "platform": platform$0.Info;
    "capabilities": Capabilities;
    "agents": { [_ in string]?: AgentStatus } | null;
    "catalog": catalog$0.CatalogItem[] | null;
    "groups": catalog$0.Group[] | null;
    "providers": { [_ in string]?: catalog$0.Provider } | null;
    "mirrors": catalog$0.Mirror[] | null;
    "paths": { [_ in string]?: string } | null;
    "backups": { [_ in string]?: boolean } | null;
    "profiles": ProfileSummary[] | null;
    "activeProfile": string | null;

    /**
     * FirstRun reports that ~/.oneagent does not exist yet, which is the signal
     * the UI uses to open onboarding instead of the overview. Agent detection is
     * not a substitute: an Agent installed before OneAgent would suppress it.
     */
    "firstRun": boolean;
    "runtimes": RuntimeStatus[] | null;
    "environment": any;
    "environmentError": string | null;
    "desktopAgents": DesktopAgentStatus[] | null;
}
