// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplyOptions controls how an import handles resources already present in the
 * local Skill library. The default is overwrite for backwards compatibility.
 */
export interface ApplyOptions {
    /**
     * overwrite | skip
     */
    "conflict_policy": string;
}

export interface Preview {
    "providers": number;
    "profiles": number;
    "mcp": number;
    "skills": string[] | null;
    "provider_new"?: string[] | null;
    "profile_new"?: string[] | null;
    "mcp_new"?: string[] | null;
    "skill_new"?: string[] | null;
    "provider_conflicts"?: string[] | null;
    "profile_conflicts"?: string[] | null;
    "mcp_conflicts"?: string[] | null;

    /**
     * SkillConflicts lists duplicate Skill IDs in the package. Existing local
     * library conflicts are resolved by the confirmation/apply layer.
     */
    "skill_conflicts"?: string[] | null;
}
