// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Preview {
    "providers": number;
    "profiles": number;
    "mcp": number;
    "skills": string[] | null;

    /**
     * SkillConflicts lists duplicate Skill IDs in the package. Existing local
     * library conflicts are resolved by the confirmation/apply layer.
     */
    "skill_conflicts"?: string[] | null;
}
