// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

export interface Registry {
    "schema_version": number;
    "servers": { [_ in string]?: ServerFact } | null;
}

export interface ServerFact {
    "variants": Variant[] | null;
}

export interface Spec {
    "type"?: string;
    "command"?: string;
    "args"?: string[] | null;
    "env"?: { [_ in string]?: string } | null;
    "cwd"?: string;
    "url"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "extensions"?: { [_ in string]?: json$0.RawMessage } | null;
}

export interface Variant {
    "agents": string[] | null;
    "spec": Spec;
}
