package install

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/MaimoryLab/OneAgent/internal/catalog"
	"github.com/MaimoryLab/OneAgent/internal/securefs"
)

// pathMarker delimits the block OneAgent owns in a shell profile. Every write
// rewrites the whole block, so a version bump cannot leave a stale directory
// behind and repeated runs cannot append duplicates.
const (
	pathMarkerBegin = "# >>> OneAgent managed runtimes >>>"
	pathMarkerEnd   = "# <<< OneAgent managed runtimes <<<"
	envScriptName   = "runtime-path.sh"
)

// GlobalPrefix is the npm global prefix for managed installs. It is deliberately
// outside the versioned runtime directory so an Agent CLI installed today keeps
// working after the locked Node version changes.
func GlobalPrefix(home string) string {
	return filepath.Join(RuntimeRoot(home), "global")
}

// GlobalBinDir is where the global prefix puts executables. npm follows the
// platform convention: a bin subdirectory on POSIX, the prefix root on Windows.
func GlobalBinDir(home, osID string) string {
	if osID == "windows" {
		return GlobalPrefix(home)
	}
	return filepath.Join(GlobalPrefix(home), "bin")
}

// ManagedPathDirs lists the directories that must be on PATH for managed
// runtimes and the Agent CLIs they install. Only installed runtimes contribute,
// so PATH never names a directory that does not exist.
func ManagedPathDirs(home, osID, arch string, manifest catalog.RuntimeManifest) []string {
	key := catalog.RuntimeArtifactKey(osID, arch)
	dirs := make([]string, 0, len(manifest.Runtimes)+1)
	for _, id := range manifest.RuntimeOrder {
		entry := manifest.Runtimes[id]
		artifact, ok := entry.Artifacts[key]
		if !ok {
			continue
		}
		if binDir := ManagedBinDir(home, id, entry, artifact); binDir != "" {
			dirs = append(dirs, binDir)
		}
	}
	if len(dirs) > 0 {
		if _, err := os.Stat(GlobalBinDir(home, osID)); err == nil {
			dirs = append(dirs, GlobalBinDir(home, osID))
		}
	}
	return dirs
}

// PersistRuntimePath records the managed directories in the user's login
// environment so an Agent CLI installed through OneAgent also resolves in the
// user's own terminal, and so a later run detects the runtime instead of
// downloading it again.
//
// It is idempotent: the POSIX path is one sourced script referenced from a
// marked block, and the Windows path rewrites only the user PATH entries that
// live under OneAgent's runtime root.
func PersistRuntimePath(ctx context.Context, runtime Runtime, filesystem securefs.Store, dirs []string) (bool, error) {
	if len(dirs) == 0 {
		return false, nil
	}
	if runtime.Platform.OS == "windows" {
		return persistWindowsPath(ctx, runtime, dirs)
	}
	return persistPosixPath(ctx, runtime, filesystem, dirs)
}

func persistPosixPath(ctx context.Context, runtime Runtime, filesystem securefs.Store, dirs []string) (bool, error) {
	script := filepath.Join(RuntimeRoot(runtime.Home), envScriptName)
	if err := filesystem.EnsurePrivateDir(ctx, RuntimeRoot(runtime.Home)); err != nil {
		return false, err
	}
	builder := &strings.Builder{}
	builder.WriteString("# Generated by OneAgent. Edits are overwritten.\n")
	for _, directory := range dirs {
		// The guard keeps a re-sourced profile from growing PATH without bound.
		fmt.Fprintf(builder, "case \":$PATH:\" in\n  *\":%s:\"*) ;;\n  *) PATH=\"%s:$PATH\" ;;\nesac\n", directory, directory)
	}
	builder.WriteString("export PATH\n")
	if _, err := filesystem.AtomicWrite(ctx, script, []byte(builder.String()), false); err != nil {
		return false, err
	}
	changed := false
	for _, profile := range shellProfiles(runtime.Home) {
		updated, err := ensureProfileBlock(ctx, filesystem, profile, script)
		if err != nil {
			return changed, err
		}
		changed = changed || updated
	}
	return changed, nil
}

// shellProfiles returns the login files to reference the script from. An
// existing file is updated; when none exists, ~/.profile is created so the
// entry is not silently dropped.
func shellProfiles(home string) []string {
	candidates := []string{".zshrc", ".bashrc", ".bash_profile", ".profile"}
	existing := make([]string, 0, len(candidates))
	for _, name := range candidates {
		path := filepath.Join(home, name)
		if _, err := os.Stat(path); err == nil {
			existing = append(existing, path)
		}
	}
	if len(existing) == 0 {
		return []string{filepath.Join(home, ".profile")}
	}
	return existing
}

func ensureProfileBlock(ctx context.Context, filesystem securefs.Store, profile, script string) (bool, error) {
	current, err := os.ReadFile(profile)
	if err != nil && !os.IsNotExist(err) {
		return false, runtimeError("Cannot read "+filepath.Base(profile), err)
	}
	block := fmt.Sprintf("%s\n[ -f \"%s\" ] && . \"%s\"\n%s\n", pathMarkerBegin, script, script, pathMarkerEnd)
	existing := string(current)
	if strings.Contains(existing, block) {
		return false, nil
	}
	updated := replaceBlock(existing, block)
	if _, err := filesystem.AtomicWrite(ctx, profile, []byte(updated), false); err != nil {
		return false, err
	}
	return true, nil
}

// replaceBlock swaps an existing OneAgent block for the new one, or appends it
// when the file has none.
func replaceBlock(content, block string) string {
	begin := strings.Index(content, pathMarkerBegin)
	end := strings.Index(content, pathMarkerEnd)
	if begin >= 0 && end > begin {
		tail := content[end+len(pathMarkerEnd):]
		return content[:begin] + block + strings.TrimPrefix(tail, "\n")
	}
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + block
}

// persistWindowsPath rewrites the user PATH through PowerShell. It replaces
// every entry under OneAgent's runtime root rather than appending, so upgrading
// the locked version cannot accumulate dead directories. The machine-wide PATH
// is never touched: that would need elevation and affect other users.
func persistWindowsPath(ctx context.Context, runtime Runtime, dirs []string) (bool, error) {
	powershell, ok := runtime.Runner.LookPath("powershell")
	if !ok || powershell == "" {
		powershell, ok = runtime.Runner.LookPath("pwsh")
	}
	if !ok || powershell == "" {
		return false, prerequisiteError("PowerShell is required to record the runtime directories on PATH")
	}
	root := RuntimeRoot(runtime.Home)
	// The script is passed as one argument with no interpolated user input
	// beyond the runtime root and the managed directories, all of which are
	// derived from HOME and the lock file rather than from a request.
	script := fmt.Sprintf(`$root = %s
$managed = @(%s)
$current = [Environment]::GetEnvironmentVariable('Path','User')
$entries = @()
if ($current) { $entries = $current -split ';' | Where-Object { $_ -ne '' } }
$kept = $entries | Where-Object { -not $_.StartsWith($root, [StringComparison]::OrdinalIgnoreCase) }
$next = @($managed + $kept) -join ';'
if ($next -ne $current) {
  [Environment]::SetEnvironmentVariable('Path', $next, 'User')
  Write-Output 'updated'
}`, powershellQuote(root), powershellList(dirs))

	result, err := runtime.command(ctx, []string{powershell, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", script}, nil, VersionCommandTimeout)
	if err != nil {
		return false, runtimeError("Cannot record the runtime directories on PATH", err)
	}
	if result.ExitCode != 0 {
		return false, runtimeError("Cannot record the runtime directories on PATH", fmt.Errorf("powershell exited with %d", result.ExitCode))
	}
	return strings.Contains(result.Stdout, "updated"), nil
}

func powershellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func powershellList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, powershellQuote(value))
	}
	return strings.Join(quoted, ",")
}
