// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Registry,
    ServerFact,
    Spec,
    Variant
} from "./models.js";
