// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CatalogItem {
    "id": string;
    "name": string;
    "group": string;
    "configMode": string;
    "guideOnly": boolean;
    "lockedVersion": string | null;
    "protocol": string | null;
    "platforms": string[] | null;
    "platformNote": string;
    "rank": number;
}

export interface Group {
    "id": string;
    "name": string;
}

export interface Mirror {
    "id": string;
    "name": string;
    "registry": string;
    "upstream": string;
    "note": string;
}

export interface Provider {
    "name": string;
    "home": string;
    "base_url": string;
    "anthropic_base_url"?: string;
    "custom"?: boolean;
    "has_key"?: boolean;
    "created_at"?: string;
}
