// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as install$0 from "../install/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

export interface AgentStatus {
    "installed": boolean;
    "configured": boolean;
    "guideOnly": boolean;
    "config": string;
    "version": string | null;
    "lockedVersion": string | null;

    /**
     * LatestVersion is the newest version published to the package registry, or
     * nil when it is not knowable -- offline, rate limited, or not an npm
     * package. It drives the update dot only, so nil means "say nothing" rather
     * than "up to date".
     */
    "latestVersion": string | null;
    "canInstall": boolean;
    "provider": string | null;
    "profileId": string | null;
    "model": string | null;
    "baseUrl": string | null;
    "updatedAt": string | null;
    "detected": DetectedConfig | null;
}

export interface AgentUpdateResult {
    "agent": string;
    "package": string;
    "command": string;
}

export interface Capabilities {
    "canInstall": { [_ in string]?: boolean } | null;

    /**
     * MissingRuntime names the runtime an Agent needs before it can be
     * installed, keyed by Agent id. An entry means canInstall is false only
     * because a bootstrappable runtime is absent, which the UI turns into a
     * "install the runtime first" prompt rather than a dead end.
     */
    "missingRuntime": { [_ in string]?: string } | null;
    "supportedAgentIds": string[] | null;
}

export interface ConversationMigrationResult {
    "files": number;
    "threads": number;
}

export interface ConversionConfig {
    "enabled": boolean;
    "listen": string;
    "api_key": string;
    "target_profile": string;
    "anthropic_model": string;
    "responses_model": string;
}

/**
 * DesktopAgentActionResult reports a local installation action. Windows Store
 * installation continues after its downloaded bootstrapper starts.
 */
export interface DesktopAgentActionResult {
    "status": string;
    "message": string;
    "refreshNeeded": boolean;
    "app": DesktopAgentStatus;
}

/**
 * DesktopAgentProfileResult is the non-secret result of applying a saved
 * profile to a desktop Agent.
 */
export interface DesktopAgentProfileResult {
    "agent": string;
    "profileId": string;
    "profileAgentId": string;
    "config"?: string;
    "restart"?: string;
    "message": string;
}

/**
 * DesktopAgentStatus is the public projection of the current desktop agent. It is
 * deliberately separate from AgentStatus: desktop and command-line agents may
 * share config, but they have different installation and version contracts.
 */
export interface DesktopAgentStatus {
    "id": string;
    "name": string;
    "installed": boolean;
    "supported": boolean;
    "path"?: string;
    "version": string | null;
    "source": string;
    "configPath"?: string;
    "configSharedWith"?: string;
    "protocol"?: string;
    "profileAgentId": string;
    "profileId": string | null;
    "packageFamily"?: string;
    "inspectionUnavailable"?: string | null;

    /**
     * Edition distinguishes regional builds of one product, so the UI can label
     * them without the region being part of Name.
     */
    "edition"?: string;

    /**
     * ManualInstall reports that BootAgent can detect and configure this app but
     * cannot fetch it. Without this the UI offered "Install the official desktop
     * application" for an Agent whose install step only returns a download link,
     * which is a button that cannot do what it says.
     */
    "manualInstall"?: boolean;
    "home"?: string;

    /**
     * Unofficial reports that the publisher is not the vendor whose model the app
     * drives, so the UI can say so instead of calling it the official application.
     */
    "unofficial"?: boolean;
}

export interface DetectedConfig {
    "baseUrl": string;
    "model": string;
    "managedByBootAgent": boolean;
    "unreadable": string | null;
}

/**
 * InstallRuntimeResult reports what the bootstrap did. PathUpdated is separate
 * from Installed because an already-downloaded runtime may still need its
 * directory recorded on the login PATH.
 */
export interface InstallRuntimeResult {
    "runtime": string;
    "installed": boolean;
    "version": string;
    "pathUpdated": boolean;
    "runtimes": RuntimeStatus[] | null;
}

export interface MCPAgentApplyResult {
    "agent": string;
    "config_updated": boolean;
    "registry_updated": boolean;
    "error"?: string;
}

export interface MCPApplyRequest {
    "changes": MCPChange[] | null;
}

export interface MCPApplyResult {
    "results": MCPAgentApplyResult[] | null;
}

export interface MCPChange {
    "id": string;
    "spec"?: mcp$0.Spec | null;
    "agents": string[] | null;
    "delete"?: boolean;
}

export interface MCPScanResult {
    "servers": MCPServerSummary[] | null;
    "eligible_agents": string[] | null;
    "diagnostics"?: string[] | null;
}

export interface MCPServerDetail {
    "id": string;
    "source_agent"?: string;
    "variants": mcp$0.Variant[] | null;
}

export interface MCPServerSummary {
    "id": string;
    "type": string;
    "agents": string[] | null;
    "variants": number;
    "conflict": boolean;
    "has_secrets": boolean;
}

/**
 * ProfileSummary is intentionally a public projection with no credential field.
 */
export interface ProfileSummary {
    "id": string;
    "label": string;
    "provider": string;
    "baseUrl": string | null;
    "model": string | null;
    "reasoningEffort"?: string;
    "context1M": boolean;
    "protocol": string;
    "activatedAt": string | null;
    "createdAt"?: string;
}

/**
 * RuntimeStatus is the public projection of one bootstrappable runtime.
 */
export type RuntimeStatus = install$0.RuntimeState;

/**
 * SaveProfileResult reports which Agents followed the Profile to its new
 * Provider or model, mirroring SaveProviderResult. Reapply failures are returned
 * per Agent rather than failing the save: the Profile record on disk is already
 * correct, and reverting it would lose the edit.
 */
export interface SaveProfileResult {
    "profile": ProfileSummary;
    "reapplied": string[] | null;
    "failures": { [_ in string]?: string } | null;
}

/**
 * SaveProviderResult reports which Agents were rewritten after the edit so the
 * UI can say so, and which ones could not be, keyed by Agent ID.
 */
export interface SaveProviderResult {
    "entry": provider$0.Entry;
    "reapplied": string[] | null;
    "failures": { [_ in string]?: string } | null;
}

/**
 * Settings holds non-secret machine-level preferences that must outlive one
 * request and do not belong to a profile.
 */
export interface Settings {
    "schema_version": number;

    /**
     * PreferMirror routes runtime archives through the mirror in
     * runtimes.lock.json and npm-managed Agents through the npmmirror registry.
     * Runtime archives keep their locked checksum verification; npm verifies
     * packages using the selected registry's metadata. uv is unaffected.
     */
    "prefer_mirror": boolean;

    /**
     * MirrorFromRegion reports that PreferMirror above is a region-derived
     * default rather than the user's own choice. The UI uses it to explain why
     * the box is already ticked. It is never persisted: it is recomputed from the
     * machine each read, and storing it would let a stale answer outlive the
     * setting that produced it.
     */
    "mirror_from_region": boolean;

    /**
     * BackupRetention is the number of historical versions kept per target.
     */
    "backup_retention": number;
}

export interface SkillAgentApplyResult {
    "agent": string;
    "target_updated": boolean;
    "registry_updated": boolean;
    "error"?: string;
}

export interface SkillApplyRequest {
    "preview_token"?: string;
    "changes": SkillChange[] | null;
}

export interface SkillApplyResult {
    "results": SkillAgentApplyResult[] | null;
}

export interface SkillBackupSummary {
    "id": string;
    "backup_id": string;
    "created_at": string;
    "variants": number;
}

export interface SkillCandidate {
    "id": string;
    "name": string;
    "description": string;
    "hash": string;
    "source": string;
    "files": number;
    "bytes": number;
    "diagnostic"?: string;
    "stored": boolean;
    "observed_agents"?: string[] | null;
}

export interface SkillChange {
    "id": string;
    "variant_hash": string;
    "targets": string[] | null;
    "delete"?: boolean;
    "delete_skill"?: boolean;
    "import_source"?: string;
}

export interface SkillImportPreview {
    "token": string;
    "candidates": SkillCandidate[] | null;
}

export interface SkillImportRequest {
    "source": string;
}

export interface SkillScanResult {
    "skills": SkillSummary[] | null;
    "candidates": SkillCandidate[] | null;
    "eligible_agents": string[] | null;
    "preview_token"?: string;
    "diagnostics"?: string[] | null;
}

export interface SkillSummary {
    "id": string;
    "name": string;
    "description": string;
    "variants": number;
    "variant_hashes": string[] | null;
    "agents": string[] | null;
    "conflict": boolean;
}

export interface SkillUninstallResult {
    "backup_id"?: string;
    "registry_updated": boolean;
    "error"?: string;
}

export interface StatusResponse {
    "apiVersion": number;
    "platform": platform$0.Info;
    "capabilities": Capabilities;
    "agents": { [_ in string]?: AgentStatus } | null;
    "catalog": catalog$0.CatalogItem[] | null;
    "groups": catalog$0.Group[] | null;
    "providers": { [_ in string]?: catalog$0.Provider } | null;
    "mirrors": catalog$0.Mirror[] | null;
    "paths": { [_ in string]?: string } | null;
    "backups": { [_ in string]?: boolean } | null;
    "profiles": ProfileSummary[] | null;
    "activeProfile": string | null;

    /**
     * FirstRun reports that ~/.bootagent does not exist yet, which is the signal
     * the UI uses to open onboarding instead of the overview. Agent detection is
     * not a substitute: an Agent installed before BootAgent would suppress it.
     */
    "firstRun": boolean;
    "migrationNotice"?: string;
    "runtimes": RuntimeStatus[] | null;
    "environment": any;
    "environmentError": string | null;
    "desktopAgents": DesktopAgentStatus[] | null;
}
