// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

export function Get(): $CancellablePromise<app$0.ConversionConfig> {
    return $Call.ByID(358447276);
}

export function Save(c: app$0.ConversionConfig): $CancellablePromise<app$0.ConversionConfig> {
    return $Call.ByID(3070277773, c);
}
