// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarketplaceService proxies the public skillhub API for the marketplace
 * pages. It exists because api.skillhub.cn only echoes CORS headers for
 * skillhub's own origins, so the renderer cannot fetch it directly; the Go
 * side has no CORS constraint. Payloads pass through as raw JSON strings --
 * normalisation stays in the frontend, which already owns it for the bundled
 * snapshot.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function FetchShowcase(): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(2412491246);
}

export function FetchSkillDetail(request: $models.SkillDetailRequest): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(613638165, request);
}

export function FetchSkillFile(request: $models.SkillDetailRequest): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(1653837074, request);
}

export function OpenExternal(request: $models.OpenExternalRequest): $CancellablePromise<void> {
    return $Call.ByID(3117329458, request);
}
