// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarketplaceService proxies the public skillhub API for the marketplace
 * pages. It exists because api.skillhub.cn only echoes CORS headers for
 * skillhub's own origins, so the renderer cannot fetch it directly; the Go
 * side has no CORS constraint. Payloads pass through as raw JSON strings --
 * normalisation stays in the frontend, which already owns it for the bundled
 * snapshot.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Catalog returns the embedded marketplace snapshot. It is parsed and
 * validated by the catalog package, keeping the renderer free of a second
 * static copy of the market data.
 */
export function Catalog(): $CancellablePromise<catalog$0.MarketplaceManifest> {
    return $Call.ByID(2296529148);
}

export function ClearRecommendationHistory(): $CancellablePromise<void> {
    return $Call.ByID(2565220155);
}

export function DeleteRecommendationHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(853357243, id);
}

/**
 * DiscoverSources returns the dynamic SkillHub and MCP Servers catalog. The
 * response uses the same MarketplaceItem contract as the embedded manifest.
 */
export function DiscoverSources(options: app$0.MarketplaceDiscoverOptions): $CancellablePromise<app$0.MarketplaceDynamicResult> {
    return $Call.ByID(1219321500, options);
}

export function FetchShowcase(): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(2412491246);
}

export function FetchSkillDetail(request: $models.SkillDetailRequest): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(613638165, request);
}

export function FetchSkillFile(request: $models.SkillDetailRequest): $CancellablePromise<$models.MarketplaceProxyResponse> {
    return $Call.ByID(1653837074, request);
}

export function ListRecommendationHistory(): $CancellablePromise<app$0.MarketplaceRecommendationHistory[] | null> {
    return $Call.ByID(638531038);
}

export function OpenExternal(request: $models.OpenExternalRequest): $CancellablePromise<void> {
    return $Call.ByID(3117329458, request);
}

/**
 * Recommend passes a bounded, public catalog projection to the selected local
 * Agent. The app layer validates both the projection and the returned item IDs.
 */
export function Recommend(request: app$0.MarketplaceRecommendRequest): $CancellablePromise<app$0.MarketplaceRecommendResult> {
    return $Call.ByID(1513373553, request);
}

/**
 * RecommendationAgents lists only installed CLI Agents whose non-interactive
 * mode can be constrained to recommendation output without write tools.
 */
export function RecommendationAgents(): $CancellablePromise<app$0.MarketplaceRecommendationAgent[] | null> {
    return $Call.ByID(386926228);
}

export function SaveRecommendationHistory(record: app$0.MarketplaceRecommendationHistory): $CancellablePromise<app$0.MarketplaceRecommendationHistory> {
    return $Call.ByID(3455853153, record);
}
