// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteProfile(request: $models.ProviderIDRequest): $CancellablePromise<$models.ProviderMutationResponse> {
    return $Call.ByID(2548092141, request);
}

export function ListProfiles(): $CancellablePromise<app$0.ProfileSummary[] | null> {
    return $Call.ByID(1660942541);
}

export function SaveProfile(request: $models.SaveProfileRequest): $CancellablePromise<app$0.SaveProfileResult> {
    return $Call.ByID(1622009115, request);
}
