// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteProvider(request: $models.ProviderIDRequest): $CancellablePromise<$models.ProviderMutationResponse> {
    return $Call.ByID(3554547039, request);
}

export function GetProvider(request: $models.ProviderIDRequest): $CancellablePromise<provider$0.Entry> {
    return $Call.ByID(768780894, request);
}

export function ListModels(request: $models.ModelsRequest): $CancellablePromise<$models.ModelsResponse> {
    return $Call.ByID(1918668407, request);
}

export function OpenGitHub(): $CancellablePromise<void> {
    return $Call.ByID(3161817574);
}

/**
 * OpenHelp opens the published help site in the user's real browser. Not an <a
 * target="_blank">: the webview has no tab to open one in, so a link either
 * navigates away from the app or does nothing.
 */
export function OpenHelp(): $CancellablePromise<void> {
    return $Call.ByID(4122050358);
}

export function OpenRegistration(request: $models.OpenRegistrationRequest): $CancellablePromise<$models.OpenRegistrationResponse> {
    return $Call.ByID(3410122324, request);
}

export function Probe(request: $models.ProbeRequest): $CancellablePromise<$models.ProbeResponse> {
    return $Call.ByID(3953621849, request);
}

export function SaveProvider(request: $models.SaveProviderRequest): $CancellablePromise<app$0.SaveProviderResult> {
    return $Call.ByID(1664240941, request);
}
