// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeService exposes the Node.js and uv bootstrap. It reuses the install
 * output listener so the UI can render runtime byte progress alongside Agent
 * install output; runtime bootstrap does not emit a fake command line.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings reads the machine-level download preferences.
 */
export function GetSettings(): $CancellablePromise<app$0.Settings> {
    return $Call.ByID(3219146295);
}

export function InstallRuntime(request: $models.InstallRuntimeRequest): $CancellablePromise<app$0.InstallRuntimeResult> {
    return $Call.ByID(3390714163, request);
}

export function ListRuntimes(): $CancellablePromise<app$0.RuntimeStatus[] | null> {
    return $Call.ByID(1842991307);
}

/**
 * SaveSettings persists the download preferences and returns what was stored.
 */
export function SaveSettings(request: app$0.SettingsPatch): $CancellablePromise<app$0.Settings> {
    return $Call.ByID(3381352702, request);
}
