// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";

export function LoadHistory(): $CancellablePromise<app$0.TaskHistoryRecord[] | null> {
    return $Call.ByID(3232226611);
}

export function SaveHistory(records: app$0.TaskHistoryRecord[] | null): $CancellablePromise<void> {
    return $Call.ByID(957362216, records);
}
