// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Read(): $CancellablePromise<string> {
    return $Call.ByID(824692923);
}

export function Write(data: string): $CancellablePromise<void> {
    return $Call.ByID(1519580634, data);
}
