// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transfer$0 from "../transfer/models.js";

export function ExportV2(providerIDs: string[] | null, profileIDs: string[] | null, mcpIDs: string[] | null, skillIDs: string[] | null): $CancellablePromise<string | null> {
    return $Call.ByID(1870855265, providerIDs, profileIDs, mcpIDs, skillIDs);
}

export function PreviewV2(data: string | null): $CancellablePromise<transfer$0.Preview> {
    return $Call.ByID(846035269, data);
}

export function Read(): $CancellablePromise<string> {
    return $Call.ByID(824692923);
}

/**
 * ReadBytes reads a JSON or v2 ZIP transfer package without converting binary
 * data through UTF-8. The frontend receives it as a base64 string via Wails.
 */
export function ReadBytes(): $CancellablePromise<string | null> {
    return $Call.ByID(257714318);
}

export function Write(data: string): $CancellablePromise<void> {
    return $Call.ByID(1519580634, data);
}

export function WriteBytes(encoded: string): $CancellablePromise<void> {
    return $Call.ByID(756993529, encoded);
}
