// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Check(): $CancellablePromise<string> {
    return $Call.ByID(2185770127);
}

export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(294692985);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2631472756);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(939852495);
}
