// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeState is the public projection of one managed runtime. It carries no
 * filesystem paths beyond the managed root so the UI cannot leak a private
 * directory layout it should not depend on.
 */
export interface RuntimeState {
    "id": string;
    "name": string;
    "command": string;
    "installed": boolean;
    "version": string;
    "lockedVersion": string;
    "managed": boolean;
    "supported": boolean;
    "note": string;
    "license": string;
    "licenseUrl": string;
    "source": string;
    "installPath": string;
    "requiredByHint"?: string;
}
